name: $(MajorVersion).$(MinorVersion)$(Rev:.r)

parameters:
  - name: Configuration
    type: string
    default: 'Release'
    values:
      - Release
      - Debug

trigger:
  batch: true
  branches:
    include:
      - main
      - release/2.0/*
  paths:
    include:
      - src/v2/Plug-ins/UTMO.Text.FileGenerator.ResourceManifestGeneration/*

resources:
  repositories:
    - repository: Templates
      type: git
      name: OneBuild\OneBuild.Pipelines.v2
      ref: refs/heads/main
      endpoint: UTMO

variables:
  - name: ProjectRoot
    value: $(Build.SourcesDirectory)/src/v2/Plug-ins/UTMO.Text.FileGenerator.ResourceManifestGeneration
  - name: Projects
    value: '$(ProjectRoot)/**/*.csproj'
  - template: UTMO.Text.FileGenerator.Build-Variables.yml@self

extends:
  template: v2/Pipelines/UserTemplates/Unified/BuildDeploy.NugetPkg.Template.yml@Templates
  parameters:
    BuildPool: Public
    BuildConfiguration: $(Configuration)
    NugetConfigPath: $(RepoRoot)/src/nuget.config
    ProjectsToBuild: '$(REPOROOT)/src/UTMO.Text.FileGenerator.sln'
    ProjectsToRestore: $(Projects)
    DotNetVersion: '9.0.x'
    DeploymentName: FileGeneratorCore
    ReleaseDisplayName: 'Publish File Generator Packages'
    UseWildcardMatch: true
    PackageSearchPattern: 'UTMO.Text.FileGenerator.ResourceManifestGeneration.*.nupkg'
    FeedSettings:
      'ConfigGen': 'internal'
      'UTMO Packages': 'external'