name: $(Year:YYYY).$(Month).$(DayOfMonth)$(Rev:.rr)

trigger: none

resources:
  repositories:
    - repository: Templates
      type: git
      name: OneBuild/OneBuild.Pipelines.v2
      ref: refs/heads/main
      endpoint: UTMO
  pipelines:
    - pipeline: latest
      source: 'UTMO.Text.FileGenerator.RendererPlugin.ScriptRunner-Official'
      trigger:
        branches:
          - main

extends:
  template: v2/Pipelines/UserTemplates/Release/Deploy.NugetPkg.v2.Template.yml@Templates
  parameters:
    ReleasePool: Public
    DeploymentName: FileGeneratorCore
    DisplayName: 'Publish File Generator Renderer Script Runner Package'
    SourcePipeline: 'UTMO.Text.FileGenerator.RendererPlugin.ScriptRunner-Official'
    UseWildcardMatch: true
    FeedSettings:
      'ConfigGen': 'internal'
      'UTMO Packages': 'external'